AWSTemplateFormatVersion: 2010-09-09

Description: Template to create an EC2 instance with existing Security Group and enable SSH

Parameters: 
  KeyName:
    Description: Name of SSH KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-062f7200baf2fa504 # Amazon Linux 2 AMI (us-east-1)
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - sg-0ad7ef5894845aca2 #sshOnlySecurityGroup (us-east-1)

      Tags:
        - Key: Name
          Value: My CF Instance
          
Outputs: 
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyEC2Instance